name: oplangc
version: 0.1.0.0
github: "Oldpug/oplangc"
license: MIT
license-file: "LICENSE.txt"
author: "Alex Ionescu"
maintainer: "alxi.2001@gmail.com"
copyright: "Copyright (C) 2019 Alex Ionescu"

extra-source-files:
- README.md

synopsis: Compiler for OpLang, an esoteric programming language
category: Compiler
description: Please see the README on GitHub at <https://github.com/Oldpug/oplangc#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- optparse-applicative
- parsec
- process
- text
- text-builder
- unordered-containers

default-extensions:
- ApplicativeDo
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

executables:
  oplangc-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    
    - -Wall
    - -Wincomplete-uni-patterns
